### ISSUE TITLE
Request for suggestion on SLabel placement and scaling

### ISSUE THREAD

**Issue by Gabetn** [eclipse/sprotty-layout#6]
Hello, 
I am using sprotty version 4.0 and am facing issues regarding SLabel placement above SNodes. Particularly, generated SLabels are direct children of the SNode and as such modify the dimensions of the SVG. This effects our ELK layout where SEdges no longer connect to the center of our SVG's rendered shape but rather the newly off-settled "center".  Additionally this reshaping of our SVG posses an issue for us as long labels further distort the boundaries and correspondingly our edges.

Is there any way to place SLabels as children of SNodes without modifying the boundaries of our SVG? Or if that is not possible, would creating new SNodes solely for our SLabels suffice.

Any insight would be appreciated.

**Comment by spoenemann** [comment]
Could you provide a JSON example of a node with label like you are creating?

Note that Sprotty has a notion of _macro layout_ (provided by ELK) and _micro layout_ (provided by Sprotty internally). ELK is able to compute positions for nested labels, see e.g. the [Node Label Placement option](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-nodelabels-placement.html). The micro layouts of Sprotty are controlled with the [layout property](https://github.com/eclipse/sprotty/blob/f5fc54535050b5eb791bf87964ff3a74cd655f47/src/graph/sgraph.ts#L75) of nodes and compartments. You should decide whether to use micro layout or macro layout for label placement. Using both at the same time will lead to problems (see also eclipse/sprotty#27).

**Comment by spoenemann** [comment]
Please open a new issue at https://github.com/eclipse/sprotty if this is still relevant.
